In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"C:\Users\kevin\Projects\data-science-ml-learning\d2l\data\1.5.26+OBBBA.GE+Data.HEA+Group+.xlsx")

In [5]:
df.head()

,opeid6,Institution,State,cip4,Major,Credential,Earnings Test Used,Fail/Pass?,Earnings Benchmark,Earnings 4 Years After Completion,Earnings More Than HS Graduate,# of Completers in Earnings Cohort,GE under OBBBA?
0,3537,Abilene Christian University,TX,3999,Theology and Religious Vocations Other. ...,Bachelor,Same-State HS Median,Pass,33298,47663,14365,19,Not GE Program
1,3537,Abilene Christian University,TX,901,Communication and Media Studies. ...,Bachelor,Same-State HS Median,Pass,33298,49202,15904,16,Not GE Program
2,3537,Abilene Christian University,TX,1313,Teacher Education and Professional Development...,Bachelor,Same-State HS Median,Pass,33298,49566,16268,24,Not GE Program
3,3537,Abilene Christian University,TX,5004,Design and Applied Arts. ...,Bachelor,Same-State HS Median,Pass,33298,49818,16520,33,Not GE Program
4,3537,Abilene Christian University,TX,1907,Human Development Family Studies and Related...,Bachelor,Same-State HS Median,Pass,33298,50525,17227,16,Not GE Program

In [14]:
math_schools = df[df["Major"].str.contains("mathematics", case = False, na = False)].copy()

In [15]:
math_schools.head()

,opeid6,Institution,State,cip4,Major,Credential,Earnings Test Used,Fail/Pass?,Earnings Benchmark,Earnings 4 Years After Completion,Earnings More Than HS Graduate,# of Completers in Earnings Cohort,GE under OBBBA?
62,2666,Adelphi University,NY,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,34350,86028,51678,16,Not GE Program
383,38193,American Public University System,WV,2703,Applied Mathematics. ...,Bachelor,National HS Median,Pass,34808,73845,39037,19,Pass OBBB-Aligned GE Earning Test
433,2115,Amherst College,MA,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,124324,89516,32,Not GE Program
567,2906,Appalachian State University,NC,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,32203,62271,30068,45,Not GE Program
614,3235,Arcadia University,PA,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,35274,66995,31721,16,Not GE Program

In [16]:
math_schools = df[
    df["Major"].str.contains("mathematics", case=False, na=False)
    & df["Credential"].eq("Bachelor")
].copy()

math_schools[[
    "Institution", "Major", "Earnings 4 Years After Completion"
]]

,Institution,Major,Earnings 4 Years After Completion
62,Adelphi University,Mathematics. ...,86028
383,American Public University System,Applied Mathematics. ...,73845
433,Amherst College,Mathematics. ...,124324
567,Appalachian State University,Mathematics. ...,62271
614,Arcadia University,Mathematics. ...,66995
...,...,...,...
32088,William & Mary,Mathematics. ...,87170
32130,William Paterson University of New Jersey,Mathematics. ...,71340
32171,Williams College,Mathematics. ...,134304
32359,Worcester State University,Mathematics. ...,57434
32394,Wright State University-Main Campus,Mathematics. ...,59848

In [17]:
schools = [
    "Massachusetts Institute of Technology",
    "Stanford University",
    "Princeton University",
    "Harvard University",
    "Duke University",
    "The University of Texas at Austin",
    "Yale University",
    "Brown University",
    "Columbia University in the City of New York",
    "Cornell University",
    "Dartmouth College",
    "University of Pennsylvania",
    "University of Chicago",
    "Northwestern University",
    "Johns Hopkins University",
    "Carnegie Mellon University",
    "California Institute of Technology",
    "University of California-Berkeley",
    "University of California-Los Angeles",
    "University of California-San Diego",
    "University of Michigan-Ann Arbor",
    "Georgia Institute of Technology-Main Campus",
    "University of Illinois Urbana-Champaign",
    "University of Washington-Seattle Campus",
    "University of Wisconsin-Madison",
    "New York University",
    "Vanderbilt University",
    "Rice University",
    "University of Notre Dame",
    "Washington University in St Louis",
    "University of Virginia-Main Campus",
    "University of North Carolina at Chapel Hill",
    "Williams College",
    "Amherst College",
]

top_math = math_schools[
    math_schools["Institution"].isin(schools)
    & math_schools["Credential"].eq("Bachelor")
].copy()

top_math.sort_values("Institution")

,opeid6,Institution,State,cip4,Major,Credential,Earnings Test Used,Fail/Pass?,Earnings Benchmark,Earnings 4 Years After Completion,Earnings More Than HS Graduate,# of Completers in Earnings Cohort,GE under OBBBA?
433,2115,Amherst College,MA,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,124324,89516,32,Not GE Program
2487,3401,Brown University,RI,2703,Applied Mathematics. ...,Bachelor,National HS Median,Pass,34808,157822,123014,50,Not GE Program
3657,3242,Carnegie Mellon University,PA,2799,Mathematics and Statistics Other. ...,Bachelor,National HS Median,Pass,34808,145741,110933,22,Not GE Program
5304,2707,Columbia University in the City of New York,NY,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,117252,82444,19,Not GE Program
5687,2711,Cornell University,NY,2611,Biomathematics Bioinformatics and Computatio...,Bachelor,National HS Median,Pass,34808,124242,89434,20,Not GE Program
5690,2711,Cornell University,NY,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,134455,99647,31,Not GE Program
6329,2573,Dartmouth College,NH,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,168580,133772,27,Not GE Program
6834,2920,Duke University,NC,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,297029,262221,17,Not GE Program
8933,1569,Georgia Institute of Technology-Main Campus,GA,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,32203,122099,89896,18,Not GE Program
9655,2155,Harvard University,MA,2703,Applied Mathematics. ...,Bachelor,National HS Median,Pass,34808,170689,135881,21,Not GE Program
11148,2077,Johns Hopkins University,MD,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,134785,99977,44,Not GE Program
13149,2178,Massachusetts Institute of Technology,MA,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,174951,140143,46,Not GE Program
15361,2785,New York University,NY,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,91832,57024,23,Not GE Program
15369,2785,New York University,NY,2799,Mathematics and Statistics Other. ...,Bachelor,National HS Median,Pass,34808,129073,94265,24,Not GE Program
16366,1739,Northwestern University,IL,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,107072,72264,31,Not GE Program
16372,1739,Northwestern University,IL,2703,Applied Mathematics. ...,Bachelor,National HS Median,Pass,34808,148740,113932,28,Not GE Program
23476,3658,The University of Texas at Austin,TX,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,33298,88434,55136,201,Not GE Program
24790,1312,University of California-Berkeley,CA,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,36082,80654,44572,49,Not GE Program
24799,1312,University of California-Berkeley,CA,2703,Applied Mathematics. ...,Bachelor,Same-State HS Median,Pass,36082,118414,82332,150,Not GE Program
24948,1315,University of California-Los Angeles,CA,2703,Applied Mathematics. ...,Bachelor,Same-State HS Median,Pass,36082,103887,67805,152,Not GE Program
24946,1315,University of California-Los Angeles,CA,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,36082,99269,63187,69,Not GE Program
25046,1317,University of California-San Diego,CA,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,36082,79015,42933,111,Not GE Program
25049,1317,University of California-San Diego,CA,2703,Applied Mathematics. ...,Bachelor,Same-State HS Median,Pass,36082,85233,49151,61,Not GE Program
25062,1317,University of California-San Diego,CA,2611,Biomathematics Bioinformatics and Computatio...,Bachelor,Same-State HS Median,Pass,36082,123320,87238,41,Not GE Program
25063,1317,University of California-San Diego,CA,3008,Mathematics and Computer Science. ...,Bachelor,Same-State HS Median,Pass,36082,137218,101136,252,Not GE Program
25330,1774,University of Chicago,IL,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,172826,138018,44,Not GE Program
26209,1775,University of Illinois Urbana-Champaign,IL,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,34808,78891,44083,57,Not GE Program
26235,1775,University of Illinois Urbana-Champaign,IL,3008,Mathematics and Computer Science. ...,Bachelor,Same-State HS Median,Pass,34808,155503,120695,37,Not GE Program
27027,2325,University of Michigan-Ann Arbor,MI,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,32989,109146,76157,85,Not GE Program
27892,2974,University of North Carolina at Chapel Hill,NC,2703,Applied Mathematics. ...,Bachelor,Same-State HS Median,Pass,32203,119839,87636,105,Not GE Program
27888,2974,University of North Carolina at Chapel Hill,NC,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,32203,101599,69396,69,Not GE Program
28337,1840,University of Notre Dame,IN,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,92118,57310,22,Not GE Program
28349,1840,University of Notre Dame,IN,2799,Mathematics and Statistics Other. ...,Bachelor,National HS Median,Pass,34808,123663,88855,46,Not GE Program
29601,3745,University of Virginia-Main Campus,VA,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,35969,91236,55267,46,Not GE Program
29677,3798,University of Washington-Seattle Campus,WA,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,39073,100127,61054,58,Not GE Program
29896,3895,University of Wisconsin-Madison,WI,2701,Mathematics. ...,Bachelor,Same-State HS Median,Pass,36491,101438,64947,92,Not GE Program
30505,3535,Vanderbilt University,TN,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,141171,106363,47,Not GE Program
31078,2520,Washington University in St Louis,MO,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,98497,63689,27,Not GE Program
32171,2229,Williams College,MA,2701,Mathematics. ...,Bachelor,National HS Median,Pass,34808,134304,99496,28,Not GE Program

In [18]:
earnings = top_math.set_index("Institution")[[
    "Earnings Benchmark",
    "Earnings 4 Years After Completion",
    "Earnings More Than HS Graduate",
]]

earnings

,Earnings Benchmark,Earnings 4 Years After Completion,Earnings More Than HS Graduate
Institution,,,
Amherst College,34808,124324,89516
Brown University,34808,157822,123014
Carnegie Mellon University,34808,145741,110933
Columbia University in the City of New York,34808,117252,82444
Cornell University,34808,124242,89434
Cornell University,34808,134455,99647
Dartmouth College,34808,168580,133772
Duke University,34808,297029,262221
Georgia Institute of Technology-Main Campus,32203,122099,89896
Harvard University,34808,170689,135881
Johns Hopkins University,34808,134785,99977
Massachusetts Institute of Technology,34808,174951,140143
New York University,34808,91832,57024
New York University,34808,129073,94265
Northwestern University,34808,107072,72264
Northwestern University,34808,148740,113932
The University of Texas at Austin,33298,88434,55136
University of California-Berkeley,36082,80654,44572
University of California-Berkeley,36082,118414,82332
University of California-Los Angeles,36082,99269,63187
University of California-Los Angeles,36082,103887,67805
University of California-San Diego,36082,79015,42933
University of California-San Diego,36082,85233,49151
University of California-San Diego,36082,123320,87238
University of California-San Diego,36082,137218,101136
University of Chicago,34808,172826,138018
University of Illinois Urbana-Champaign,34808,78891,44083
University of Illinois Urbana-Champaign,34808,155503,120695
University of Michigan-Ann Arbor,32989,109146,76157
University of North Carolina at Chapel Hill,32203,101599,69396
University of North Carolina at Chapel Hill,32203,119839,87636
University of Notre Dame,34808,92118,57310
University of Notre Dame,34808,123663,88855
University of Virginia-Main Campus,35969,91236,55267
University of Washington-Seattle Campus,39073,100127,61054
University of Wisconsin-Madison,36491,101438,64947
Vanderbilt University,34808,141171,106363
Washington University in St Louis,34808,98497,63689
Williams College,34808,134304,99496

In [19]:
earnings.sort_values("Earnings 4 Years After Completion", ascending=False)

,Earnings Benchmark,Earnings 4 Years After Completion,Earnings More Than HS Graduate
Institution,,,
Duke University,34808,297029,262221
Massachusetts Institute of Technology,34808,174951,140143
University of Chicago,34808,172826,138018
Harvard University,34808,170689,135881
Dartmouth College,34808,168580,133772
Brown University,34808,157822,123014
University of Illinois Urbana-Champaign,34808,155503,120695
Northwestern University,34808,148740,113932
Carnegie Mellon University,34808,145741,110933
Vanderbilt University,34808,141171,106363
University of California-San Diego,36082,137218,101136
Johns Hopkins University,34808,134785,99977
Cornell University,34808,134455,99647
Williams College,34808,134304,99496
New York University,34808,129073,94265
Amherst College,34808,124324,89516
Cornell University,34808,124242,89434
University of Notre Dame,34808,123663,88855
University of California-San Diego,36082,123320,87238
Georgia Institute of Technology-Main Campus,32203,122099,89896
University of North Carolina at Chapel Hill,32203,119839,87636
University of California-Berkeley,36082,118414,82332
Columbia University in the City of New York,34808,117252,82444
University of Michigan-Ann Arbor,32989,109146,76157
Northwestern University,34808,107072,72264
University of California-Los Angeles,36082,103887,67805
University of North Carolina at Chapel Hill,32203,101599,69396
University of Wisconsin-Madison,36491,101438,64947
University of Washington-Seattle Campus,39073,100127,61054
University of California-Los Angeles,36082,99269,63187
Washington University in St Louis,34808,98497,63689
University of Notre Dame,34808,92118,57310
New York University,34808,91832,57024
University of Virginia-Main Campus,35969,91236,55267
The University of Texas at Austin,33298,88434,55136
University of California-San Diego,36082,85233,49151
University of California-Berkeley,36082,80654,44572
University of California-San Diego,36082,79015,42933
University of Illinois Urbana-Champaign,34808,78891,44083

In [22]:
highest_earners = df.nlargest(
    25, "Earnings 4 Years After Completion"
)[[
    "Institution",
    "Major",
    "Credential",
    "Earnings 4 Years After Completion",
]].copy()

highest_earners

,Institution,Major,Credential,Earnings 4 Years After Completion
6834,Duke University,Mathematics. ...,Bachelor,297029
3664,Carnegie Mellon University,Computer Science. ...,Bachelor,268121
3663,Carnegie Mellon University,Electrical Electronics and Communications En...,Bachelor,250168
28471,University of Pennsylvania,Computer and Information Sciences General. ...,Bachelor,241380
9657,Harvard University,Statistics. ...,Bachelor,230876
24958,University of California-Los Angeles,Computer Engineering. ...,Bachelor,228705
13150,Massachusetts Institute of Technology,Computer Science. ...,Bachelor,225141
5696,Cornell University,Computer Science. ...,Bachelor,223309
17844,Princeton University,Computer Science. ...,Bachelor,217973
17680,Pomona College,Computer Science. ...,Bachelor,217051
24957,University of California-Los Angeles,Computer and Information Sciences General. ...,Bachelor,216722
21380,Stanford University,Computer Science. ...,Bachelor,214907
2488,Brown University,Computer Science. ...,Bachelor,214479
32173,Williams College,Computer Science. ...,Bachelor,209574
24808,University of California-Berkeley,Computer Science. ...,Bachelor,204379
9656,Harvard University,Computer Science. ...,Bachelor,203169
28470,University of Pennsylvania,Finance and Financial Management Services. ...,Bachelor,202069
6330,Dartmouth College,Computer Science. ...,Bachelor,201702
24807,University of California-Berkeley,Electrical Electronics and Communications En...,Bachelor,200543
2700,California Institute of Technology,Computer Science. ...,Bachelor,200511
9659,Harvey Mudd College,Computer Science. ...,Bachelor,198257
11149,Johns Hopkins University,Computer and Information Sciences General. ...,Bachelor,196467
6833,Duke University,Computer Science. ...,Bachelor,195809
5309,Columbia University in the City of New York,Computer Engineering. ...,Bachelor,194365
29215,University of Southern California,Computer Science. ...,Bachelor,192897

In [23]:
highest_earners = df.nlargest(
    25, "Earnings 4 Years After Completion"
)[[
    "Institution",
    "Major",
    "Credential",
    "Earnings 4 Years After Completion",
    "# of Completers in Earnings Cohort",
]].copy()

highest_earners

,Institution,Major,Credential,Earnings 4 Years After Completion,# of Completers in Earnings Cohort
6834,Duke University,Mathematics. ...,Bachelor,297029,17
3664,Carnegie Mellon University,Computer Science. ...,Bachelor,268121,121
3663,Carnegie Mellon University,Electrical Electronics and Communications En...,Bachelor,250168,113
28471,University of Pennsylvania,Computer and Information Sciences General. ...,Bachelor,241380,40
9657,Harvard University,Statistics. ...,Bachelor,230876,17
24958,University of California-Los Angeles,Computer Engineering. ...,Bachelor,228705,28
13150,Massachusetts Institute of Technology,Computer Science. ...,Bachelor,225141,213
5696,Cornell University,Computer Science. ...,Bachelor,223309,296
17844,Princeton University,Computer Science. ...,Bachelor,217973,30
17680,Pomona College,Computer Science. ...,Bachelor,217051,21
24957,University of California-Los Angeles,Computer and Information Sciences General. ...,Bachelor,216722,136
21380,Stanford University,Computer Science. ...,Bachelor,214907,108
2488,Brown University,Computer Science. ...,Bachelor,214479,116
32173,Williams College,Computer Science. ...,Bachelor,209574,35
24808,University of California-Berkeley,Computer Science. ...,Bachelor,204379,304
9656,Harvard University,Computer Science. ...,Bachelor,203169,47
28470,University of Pennsylvania,Finance and Financial Management Services. ...,Bachelor,202069,111
6330,Dartmouth College,Computer Science. ...,Bachelor,201702,62
24807,University of California-Berkeley,Electrical Electronics and Communications En...,Bachelor,200543,188
2700,California Institute of Technology,Computer Science. ...,Bachelor,200511,25
9659,Harvey Mudd College,Computer Science. ...,Bachelor,198257,33
11149,Johns Hopkins University,Computer and Information Sciences General. ...,Bachelor,196467,58
6833,Duke University,Computer Science. ...,Bachelor,195809,167
5309,Columbia University in the City of New York,Computer Engineering. ...,Bachelor,194365,18
29215,University of Southern California,Computer Science. ...,Bachelor,192897,142